-- Enforce RLS on sensitive tables
ALTER TABLE IF EXISTS public.security_events ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.security_events FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.gmail_tokens ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.gmail_tokens FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.gmail_token_access_log ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.gmail_token_access_log FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.contact_submissions ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.contact_submissions FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.leads ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.leads FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.subscribers ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.subscribers FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.emergency_service_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.emergency_service_requests FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.emergency_test_results ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.emergency_test_results FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.video_analytics ENABLE ROW LEVEL SECURITY; ALTER TABLE IF EXISTS public.video_analytics FORCE ROW LEVEL SECURITY;